Stark/Stark/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stark.Models;

namespace Stark.Controllers
{
    public class ReportsController : Controller
    {
        private readonly starkContext _context;

        public ReportsController(starkContext context)
        {
            _context = context;
        }

        //Counts the number of reviews for a specific License Plate - passed as a parameter
        public int Counter(string plate)
        {
            int counter;
            counter = _context.Review.Count(s => s.Licence.Plate == plate);
            return counter;
        }
        //Counts the number of reviews for a specific License Id, badge type and optional wight - passed as parameters
        public double Counter(int id, int type, int weight=1)
        {
            double counter;
            counter = _context.Review.Count(s => s.Badge.Type == type && s.LicenceId == id);
            return counter*type*weight;
        }

        //Generates a key value pair list - License plate as key and the score as value
        //Score - is a weighted average - cont
        //Each review has a type - an int value  - 0 for the worst, 1 for the bad , 3 for the good and 4 for the excellent - cont
        //For each plate, all its reviews are added and the sum is then divided by the number of reviews for said plate - default weight is 1.
        
        public IDictionary<string, double> GetScore()
        {
            IDictionary<string, double> scores = new Dictionary<string, double>();

            foreach (var item in _context.Cars)
            {
                scores.Add(item.Plate, Math.Round((Counter(item.LicenceId, 0) + Counter(item.LicenceId, 1) + Counter(item.LicenceId, 3) + Counter(item.LicenceId, 4))/Counter(item.Plate), 2));

            }
            return scores;
        }

        //Retrives the Id of a specific license plate  - passed as a parameter
        public int GetId(string plate)
        {
            int id;
            Cars ob = _context.Cars.Where(s=>s.Plate==plate).FirstOrDefault();
            id = ob.LicenceId;
            return id;
        }

        //Main method that instances the view
        public IActionResult Index()
        {
            var ScoreList = GetScore().ToList();
            ScoreList.Sort((pair1, pair2) => pair2.Value.CompareTo(pair1.Value)); //sorting the view by descending score

            //List of object of the ViewModel "CarsViewcs"
            List<CarsViewcs> All=new List<CarsViewcs>();

            int i = 1; //used to memorise the position in the ranking

            //Adding all the records 
            foreach (var item in ScoreList)
            {
                CarsViewcs c = new CarsViewcs { LicenceId=GetId(item.Key), Position=i, Plate = item.Key, ReviewCount = Counter(item.Key), Score = item.Value };
                if (c.ReviewCount > 0)
                    {
                    All.Add(c);
                    ++i;
                }

            }
            return View(All);
        }
    }
}

Stark/Stark/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stark.Models;

namespace Stark.Controllers
{
    public class ReviewsController : Controller
    {

        private readonly starkContext _context;

        public ReviewsController(starkContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index(string sortOrder,string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "plate_desc" : ""; //used for sort button in the View
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";//used for sort button in the View
            ViewData["CurrentFilter"] = searchString; //used for search button in the View
            IQueryable<Review> starkContext = _context.Review.Include(r => r.Badge).Include(r => r.Licence);
            if (!String.IsNullOrEmpty(searchString)) //if anything was entered in the search box
            {
                //context passed to view is now limited to only the records that match searchString - operator OR used so all the columns can be filtered
                starkContext =_context.Review.Include(r => r.Badge).Include(r => r.Licence).Where(r => r.Licence.Plate.ToUpper().Contains(searchString.ToUpper().Trim())||r.Badge.Title.ToUpper().Contains(searchString.ToUpper().Trim())||r.UserIp.Contains(searchString.Trim())||((BadgeType)r.Badge.Type).ToString().Contains(searchString.Trim())||r.CreateDate.Date.ToString().Contains(searchString.Trim()));
            }
            switch (sortOrder) //used to determine which way the context is Ordered 
            {
                case "plate_desc":
                    starkContext = starkContext.OrderByDescending(s => s.Licence.Plate);
                    break;
                case "Date":
                    starkContext = starkContext.OrderBy(s => s.CreateDate);
                    break;
                case "date_desc":
                    starkContext = starkContext.OrderByDescending(s => s.CreateDate);
                    break;
                default:
                    starkContext = starkContext.OrderBy(s => s.CreateDate);
                    break;
            }
            return View(await starkContext.ToListAsync());
            
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var review = await _context.Review
                .Include(r => r.Badge)
                .Include(r => r.Licence)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }
        // GET: Reviews/Create when the Plate already exists in the DB
        public IActionResult CreateExists(string sequence, bool? saveChangesError = false)
        {
            //"badges" used for the View - all the field of a Badge record are now visible in the dropdown
            var badges = _context.Badge.Select(m => new { Text = m.Title + " -- " + (BadgeType)Enum.ToObject(typeof(BadgeType), m.Type) + " -- " + m.Description, Value = m.BadgeId }).ToList(); //for the View - all the field of a Badge record are visible

            //"aux" - selects the plate from the db (matching it with the parameter "sequence" that came from Cars POST redirect
            var aux = _context.Cars.Where(r => r.Plate == sequence);
            ViewData["BadgeId"] = new SelectList(badges, "Value", "Text");
            ViewData["LicenceId"] = new SelectList(aux, "LicenceId", "Plate");
            if (saveChangesError.GetValueOrDefault()) //spam check
            {
                ViewData["ErrorMessage"] ="You've recently reviewed this driver. You can review the same driver once every 72 hours.";
            }

            return View();
        }

        // GET: Reviews/Create when the Plate did not exist in the DB before the Upload POST call (that redirected to a Cars Create POST call)
        public IActionResult CreateNew(int id)
        {
            //"badges" used for the View - all the field of a Badge record are now visible in the dropdown
            var badges = _context.Badge.Select(m => new { Text = m.Title + " -- " + (BadgeType)Enum.ToObject(typeof(BadgeType), m.Type) + " -- " + m.Description, Value = m.BadgeId }).ToList();
            //"aux" - selects the (freshly added) plate from the db (matching it with the parameter "id" that came from Cars POST redirect
            var aux = _context.Cars.Where(r => r.LicenceId == id);
            ViewData["BadgeId"] = new SelectList(badges, "Value", "Text");
            ViewData["LicenceId"] = new SelectList(aux, "LicenceId", "Plate");
            return View();
        }
        // GET: Reviews/Create - only called when adding Reviews "the admin way"
        public IActionResult Create()
        {
            var badges = _context.Badge.Select(m => new { Text = m.Title + " -- " + (BadgeType)Enum.ToObject(typeof(BadgeType), m.Type) + " -- " + m.Description, Value = m.BadgeId }).ToList();
            ViewData["BadgeId"] = new SelectList(badges, "Value", "Text");
            ViewData["LicenceId"] = new SelectList(_context.Cars, "LicenceId", "Plate");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,LicenceId,BadgeId,CreateDate,UserIp")] Review review)
        {
            //"badges" used for the View - all the field of a Badge record are now visible in the dropdown
            var badges = _context.Badge.Select(m => new { Text = m.Title + " -- " + (BadgeType)Enum.ToObject(typeof(BadgeType), m.Type) + " -- " + m.Description, Value = m.BadgeId }).ToList();
            //userip  - local variable used to get the IP of the user to be then assigned to the UserIp property of Review
            string userip = System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).AddressList.GetValue(1).ToString();
            review.UserIp = userip;
            //spam - used to determine if the same user (same ip) has already reviewed the same Car (same LicenseId) in the last 72 hours
            bool spam = _context.Review.Any(s => s.LicenceId == review.LicenceId && s.UserIp == review.UserIp && (review.CreateDate.Subtract(s.CreateDate).TotalDays<3.0d));
            if ((ModelState.IsValid)&&(!spam))
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            if (spam==true)
            {
                return RedirectToAction("CreateExists", new { saveChangesError = true }); //for generating a spam error message in the View
            }
            ViewData["BadgeId"] = new SelectList(badges, "Value", "Text");
            ViewData["LicenceId"] = new SelectList(_context.Cars, "LicenceId", "Plate", review.LicenceId);
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var badges = _context.Badge.Select(m => new { Text = m.Title + " -- " + (BadgeType)Enum.ToObject(typeof(BadgeType), m.Type) + " -- " + m.Description, Value = m.BadgeId }).ToList();
            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["BadgeId"] = new SelectList(badges, "Value", "Text");
            ViewData["LicenceId"] = new SelectList(_context.Cars, "LicenceId", "Plate", review.LicenceId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,LicenceId,BadgeId, CreateDate,UserIp")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var badges = _context.Badge.Select(m => new { Text = m.Title + " -- " + (BadgeType)Enum.ToObject(typeof(BadgeType), m.Type) + " -- " + m.Description, Value = m.BadgeId }).ToList();
            ViewData["BadgeId"] = new SelectList(badges, "Value", "Text");
            ViewData["LicenceId"] = new SelectList(_context.Cars, "LicenceId", "Plate", review.LicenceId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {

Stark/Stark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Stark</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="dropdown" style="float:left;">
                <button class="dropbtn"><img src="~/images/stark.png" height="20px" width="40px"/></button>
                <div class="dropdown-content" style="left:0;">
                    <a asp-area="" asp-controller="Reviews" asp-action="Index">Review</a>
                    <a asp-area="" asp-controller="Upload" asp-action="Index">Upload</a>
                    <a asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                    <a asp-area="" asp-controller="Home" asp-action="Index">About</a>
                </div>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>           
            </div>
        </div>
    </nav>
   


    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>